version: "3.8"

volumes:
  excluded_target:

services:
  production_editor: &base
    build:
      target: build
      context: .
    environment:
      VIDEO_DIRECTORY: data/mp4
      AUDIO_DIRECTORY: data/mp3
      PREPEND_TEMPLATE_DIRECTORY: data/prepend_templates
      PREPEND_INPUT_DIRECTORY: data/prepend_input
      PREPEND_OUTPUT_DIRECTORY: data/prepend_output
    volumes:
      - ./:/home/build/app
      - excluded_target:/home/build/app/target

  unit_tests:
    <<: *base
    command: sbt clean test

  dev:
    <<: *base
    stdin_open: true
    tty: true
    command: /bin/bash

  run:
    <<: *base
    stdin_open: true
    tty: true
    command: ./target/universal/stage/bin/video-and-audio-editor
