version: "3.8"
services:
  production_editor: &base
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      VIDEO_DIRECTORY: ${HOME}/dev/video-to-audio-editor/data/mp4
      AUDIO_DIRECTORY: ${HOME}/dev/video-to-audio-editor/data/mp3

  unit_tests:
    <<: *base
    command: sbt clean test

  dev:
    <<: *base
    stdin_open: true
    tty: true
    command: /bin/bash
