version: "3.8"
services:
  production_editor: &base
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      VIDEO_DIRECTORY: data/mp4
      AUDIO_DIRECTORY: data/mp3
      PREPEND_TEMPLATE_FILE: data/prepend_templates
      PREPEND_INPUT_DIRECTORY: data/prepend_input
      PREPEND_OUTPUT_DIRECTORY: data/prepend_output
    volumes:
      - ${HOME}/dev/video-to-audio-editor/data:/home/build/app/data

  unit_tests:
    <<: *base
    command: sbt clean test

  dev:
    <<: *base
    stdin_open: true
    tty: true
    command: /bin/bash
