#!/bin/bash

set -euxo pipefail

docker-compose --file ./docker/docker-compose.yml build build
docker-compose --file ./docker/docker-compose.yml down
docker-compose --file ./docker/docker-compose.yml run build
