#!/bin/bash

set -euxo pipefail

docker-compose --file ./docker/docker-compose.yml build dev
docker-compose --file ./docker/docker-compose.yml down
docker-compose --file ./docker/docker-compose.yml run --rm dev
