#!/bin/bash

set -euxo pipefail

docker-compose --file ./docker-compose.yml build unit_tests
docker-compose --file ./docker-compose.yml down
docker-compose --file ./docker-compose.yml run unit_tests

